// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsG-NW7DzskqQlhQ5RErXnm7UhSM8g4QA',
    appId: '1:296785568208:web:d3569623f24acebd4059d5',
    messagingSenderId: '296785568208',
    projectId: 'peace-aeb6c',
    authDomain: 'peace-aeb6c.firebaseapp.com',
    databaseURL: 'https://peace-aeb6c-default-rtdb.firebaseio.com',
    storageBucket: 'peace-aeb6c.appspot.com',
    measurementId: 'G-ETHFBZVLBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXy5oXFVRI2rhS_L0BA3789E_5Z9vXY4k',
    appId: '1:296785568208:android:deb8ff51e6a94cb64059d5',
    messagingSenderId: '296785568208',
    projectId: 'peace-aeb6c',
    databaseURL: 'https://peace-aeb6c-default-rtdb.firebaseio.com',
    storageBucket: 'peace-aeb6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFX5VGUkPoZj79M81WaDVmMW9pmJIRS24',
    appId: '1:296785568208:ios:d895b30f926032f84059d5',
    messagingSenderId: '296785568208',
    projectId: 'peace-aeb6c',
    databaseURL: 'https://peace-aeb6c-default-rtdb.firebaseio.com',
    storageBucket: 'peace-aeb6c.appspot.com',
    iosBundleId: 'com.example.splashPractices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFX5VGUkPoZj79M81WaDVmMW9pmJIRS24',
    appId: '1:296785568208:ios:ce7d9ff2280d4d0e4059d5',
    messagingSenderId: '296785568208',
    projectId: 'peace-aeb6c',
    databaseURL: 'https://peace-aeb6c-default-rtdb.firebaseio.com',
    storageBucket: 'peace-aeb6c.appspot.com',
    iosBundleId: 'com.example.splashPractices.RunnerTests',
  );
}
